# Code generated by SdkContractGenerator. DO NOT EDIT.

CONTRACT = {
    "modify-video": {
        "models": ["luma-modify-video"],
        "fields_by_model": {
            "luma-modify-video": {
                "prompt": {
                    "required": True
                },
                "source_video_url": {
                    "required": True
                }
            }
        }
    }
}
